#!/usr/bin/env node
'use strict'

/* -----------------------------------------------------------------------------
 * success
 * -------------------------------------------------------------------------- */
const fn = async function () {
  await Promise.resolve()
  process.stdout.write('success')
  process.exit(0)
}

fn()
